# https://github.com/hvr/multi-ghc-travis
# NB: don't set `language: haskell` here

# The following enables several GHC versions to be tested; often it's enough to test only against the last release in a major GHC version. Feel free to omit lines listings versions you don't need/want testing for.
env:
 - CABALVER=1.18 GHCVER=7.6.3
 - CABALVER=1.18 GHCVER=7.8.4 
 - CABALVER=1.22 GHCVER=7.10.1
 - CABALVER=1.22 GHCVER=7.10.2

# Note: the distinction between `before_install` and `install` is not important.
before_install:
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$HOME/.cabal/bin:$PATH
 - travis_retry git clone https://github.com/Soostone/katip.git
 - mv katip/katip/katip.cabal katip/katip/katip.cabal.orig
 - cp katip-cabal/katip.cabal katip/katip/katip.cabal

install:
 - cabal --version
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - travis_retry cabal update

 - |
   if [ ${GHCVER%.*} = "7.10" ]; then
     travis_retry cabal install katip/katip/katip.cabal --ghc-options=-XFlexibleContexts --force-reinstalls 
     travis_retry cabal install lcs --ghc-options=-XFlexibleContexts --force-reinstalls
   else
     travis_retry cabal install katip/katip/katip.cabal --force-reinstalls
   fi

script:
 - cabal install

 # tests that a source-distribution can be generated
 - cabal sdist

 # check that the generated source-distribution can be built & installed
 - SRC_TGZ=$(cabal info . | awk '{print $2;exit}').tar.gz &&
   (cd dist && cabal install --force-reinstalls "$SRC_TGZ")

# EOF
